#config.yml

# Craftystarter plugin by ares06
# v1.1

# Enable or disable the plugin
Enabled: true

# Enable or disable bungeecord join feature
BungeeCordFeatures: false

# Configuration for server1
# Server name must be the same as your bungecord configuration
# If you want to use bungeecord join feature

server1:
  enabled: false
  url: "https://yourcraftyip.com"
  token: "your_crafty_api"
  id: "your_server_id"
  ip: "your_server_ip"

# You can continue adding more server configurations in a similar format
