name: craftystarter
author: ares06
version: '${project.version}'
main: ares06.craftystarter.Craftystarter
api-version: '1.20'
commands:
  joinserver:
    description: Join a server
    usage: /joinserver <server_name>